# Generated by Django 5.2.8 on 2025-11-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_full_name_profile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_code', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('food', 'Food & Nutrition'), ('toys', 'Toys & Play'), ('accessories', 'Pet Accessories'), ('grooming', 'Grooming Products'), ('health', 'Health & Medicines'), ('housing', 'Housing & Bedding'), ('training', 'Training Supplies'), ('electronics', 'Electronics'), ('others', 'Others')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
