# Generated by Django 5.2.8 on 2025-11-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='stock_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Nutrition'), ('toys', 'Toys & Play'), ('accessories', 'Pet Accessories'), ('grooming', 'Grooming Products'), ('health', 'Health & Medicines'), ('housing', 'Housing & Bedding'), ('training', 'Training Supplies'), ('others', 'Others')], max_length=50),
        ),
    ]
