# Generated by Django 5.2.7 on 2025-11-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customer_alter_product_category_cart_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_number',
            field=models.IntegerField(default=1),
        ),
    ]
